# Changes here will be overwritten by Copier
_commit: 9f61b35
_src_path: https://github.com/python-project-templates/base.git
add_extension: site-sveltekit
brand_name: Example
github: python-project-templates
project_description: A fast, accessible SvelteKit website.
project_name: javascript-template-site-sveltekit
site_adapter: static
site_url: https://example.com
